server:
  port: 8181

logging:
  level:
    com.gfmartinez.hexagonalarchitecture: DEBUG

spring:
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=incidence&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
#    platform: postgres
#    schema: classpath:init-schema.sql
#    initialization-mode: always
springdoc:
  swagger-ui:
    enabled: true